@sender_id = 00cfbb2f-1f72-4494-94c2-36ae114f223a
@receiver_id = cd8200b4-ef25-4908-86e4-4979ccf3efea
@pickup_location_id = {pickup_location_id}
@delivery_location_id = {delivery_location_id}
@status_id = {status_id}
@parcel_id = {parcel_id}
@courier_id = {courier_id}sys
@user_id = 4119ba95-b792-4ed7-bdd1-127196ef3479
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhOGQyN2EzOS02OTcxLTQxMTctYTk0OS1mNjg2ZDNlMmE0NjciLCJlbWFpbCI6InZpY3RvcmlhY2xhcmU0MEBnbWFpbC5jb20iLCJpYXQiOjE3NTM0NDU0NTAsImV4cCI6MTc1MzUzMTg1MH0.3tfUML1hQUnedlxkZolNL4wkZZ_Rcnoc5Kj5zBm8g3k

### Register Admin
POST http://localhost:3000/admin/register
Content-Type: application/json

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "victoriaclare400@gmail.com",
  "password": "Clare@040",
  "phone": "+254700000010"
}

### Login Admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "victoriaclare40@gmail.com",
  "password": "Clare@040"
}

### Create Parcel (Admin)
POST http://localhost:3000/admin/parcels
Content-Type: application/json

{
  "senderName": "John Doe",
  "senderEmail": "john.doe@example.com",
  "senderPhone": "+254712345678",
  "senderAddress": "123 Main St, Nairobi, Kenya",
  "receiverName": "Jane Smith",
  "receiverEmail": "jane.smith@example.com",
  "receiverPhone": "+254798765432",
  "receiverAddress": "456 Oak Ave, Mombasa, Kenya",
  "weight": 2.5,
  "price": 800
}

### Assign Courier
PATCH http://localhost:3000/admin/parcels/{{parcel_id}}/assign-courier
Content-Type: application/json

{
  "courierId": "{{courier_id}}"
}


### List Parcels
GET http://localhost:3000/admin/parcels

### List Users
GET http://localhost:3000/admin/users

### List Couriers
GET http://localhost:3000/admin/couriers 

### Get User By ID (Admin)
GET http://localhost:3000/admin/users/4119ba95-b792-4ed7-bdd1-127196ef3479

### Update User (Admin)
PATCH http://localhost:3000/admin/users/{{user_id}}
Content-Type: application/json

{
  "name": "Courier One",
  "email": "victoriaclare400@gmail.com",
  "phone": "+254700000010",
  "password": "Clare@040",
  "role": "COURIER"
}

### Delete User (Admin)
DELETE http://localhost:3000/admin/users/4119ba95-b792-4ed7-bdd1-127196ef3479

### Get Parcel By ID (Admin)
GET http://localhost:3000/admin/parcels/{{parcel_id}}

### Update Parcel (Admin)
PATCH http://localhost:3000/admin/parcels/{{parcel_id}}
Content-Type: application/json

{
  "weight": 3.0,
  "price": 120
}

### Delete Parcel (Admin)
DELETE http://localhost:3000/admin/parcels/{{parcel_id}} 