@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MDhhYWVhNC0xNDY0LTRhYzQtYmQyOS02NmIyYjIwZWQyOTEiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NTMzOTk3OTYsImV4cCI6MTc1MzQ4NjE5Nn0.GkwQQNARSmTg9NGTzZpFlbCfTwxLqlmi0-hi1hUvbbM
### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johny@example.com",
  "password": "StrongPassword123!",
  "phone": "+254712345679"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "victoriaclare400@gmail.com",
  "password": "Clare@040"
}

### Get Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer {{access_token}}

### Refresh Token
POST http://localhost:3000/auth/refresh
Authorization: Bearer {{access_token}}

### Validate Token
POST http://localhost:3000/auth/validate
Authorization: Bearer {{access_token}}

 