### Create Parcel (using address and status name)
POST http://localhost:3000/parcels
Content-Type: application/json

{
  "senderId": "0bc50219-a968-485d-8d62-206defa00a95",
  "receiverId": "f94435ef-77d6-41ec-9579-4d7c8babd3bc",
  "weight": 2.5,
  "price": 100,
  "pickupAddress": "Moi Avenue, Nairobi",
  "deliveryAddress": "Kenyatta Avenue, Nairobi",
  "statusName": "PENDING"
}

### Get Sent Parcels
GET http://localhost:3000/parcels/sent?userId={{user_id}}

### Get Received Parcels
GET http://localhost:3000/parcels/received?userId={{user_id}}

### Get Assigned Parcels (Courier)
GET http://localhost:3000/parcels/assigned?courierId={{courier_id}}

### Get Parcel By ID
GET http://localhost:3000/parcels/{{parcel_id}}

### Update Parcel Status (by status name)
PATCH http://localhost:3000/parcels/{{parcel_id}}/status
Content-Type: application/json

{
  "statusName": "DELIVERED"
}